"""Durable object storage abstraction.

On Vercel, serverless functions have a read-only filesystem (aside from an
unreliable /tmp), so anything written to local disk today — dataset parquet
snapshots, trained model bundles, payment screenshots — would silently not
survive between requests. This module gives every caller one small interface
(`put_bytes` / `get_bytes` / `delete`) that:

  - uses Vercel Blob (https://vercel.com/docs/vercel-blob) for real,
    persistent storage when a BLOB_READ_WRITE_TOKEN is configured (this is
    what production on Vercel must use), and
  - falls back to local disk when it isn't (local/dev use, exactly like
    today), so nothing breaks for anyone not deploying to Vercel yet.

Honesty note: the Vercel Blob branch is implemented against Vercel's
documented REST API (the same one their JS SDK calls under the hood), but
could not be exercised against a *live* Blob store in this sandbox (no token
was available here). The local-disk branch shares the exact same function
signatures and has been exercised directly. Test the Blob branch with a
small upload right after deploying and before relying on it for real user
data.
"""
import os
from pathlib import Path

import requests

from ..config import DATA_DIR

BLOB_TOKEN = os.environ.get("BLOB_READ_WRITE_TOKEN", "")
BLOB_ENABLED = bool(BLOB_TOKEN)
BLOB_API_BASE = "https://blob.vercel-storage.com"

# Local fallback root — same on-disk location the app has always used. Only
# created when actually needed (BLOB_ENABLED is False), so a production
# deployment with Blob configured never touches the read-only filesystem.
_LOCAL_ROOT = DATA_DIR / "blobs"
if not BLOB_ENABLED:
    try:
        _LOCAL_ROOT.mkdir(parents=True, exist_ok=True)
    except OSError:
        pass


class BlobError(Exception):
    pass


def _local_path(key: str) -> Path:
    # keys are always generated by us (uuid-based filenames), never
    # user-controlled, so a straightforward join is safe here.
    return _LOCAL_ROOT / key


def put_bytes(key: str, data: bytes, content_type: str = "application/octet-stream") -> str:
    """Stores `data` under `key`. Returns a locator string — a Blob URL in
    production, a local file path in dev/fallback — that must be passed back
    to get_bytes()/delete() unchanged; callers should treat it as opaque and
    persist it (e.g. in the DB) rather than reconstructing it themselves."""
    if not BLOB_ENABLED:
        path = _local_path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        return str(path)

    resp = requests.put(
        f"{BLOB_API_BASE}/{key}",
        data=data,
        headers={
            "authorization": f"Bearer {BLOB_TOKEN}",
            "x-content-type": content_type,
            "x-api-version": "7",
        },
        timeout=60,
    )
    if resp.status_code >= 300:
        raise BlobError(f"Vercel Blob upload failed ({resp.status_code}): {resp.text[:300]}")
    return resp.json()["url"]


def get_bytes(locator: str) -> bytes:
    if not BLOB_ENABLED:
        return Path(locator).read_bytes()
    resp = requests.get(locator, timeout=60)
    if resp.status_code >= 300:
        raise BlobError(f"Vercel Blob download failed ({resp.status_code}) for {locator}")
    return resp.content


def delete(locator: str) -> None:
    if not BLOB_ENABLED:
        try:
            Path(locator).unlink(missing_ok=True)
        except OSError:
            pass
        return
    try:
        requests.delete(
            BLOB_API_BASE,
            params={"url": locator},
            headers={"authorization": f"Bearer {BLOB_TOKEN}"},
            timeout=30,
        )
    except requests.RequestException:
        pass  # best-effort cleanup; never fail the caller's request over it
